services:
  redis:
    image: redis
    platform: linux/x86_64
    container_name: jager-redis
    networks:
      - jager-net

  db:
    image: clickhouse/clickhouse-server
    platform: linux/x86_64
    container_name: jager-db
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9009:9009'
    environment:
      - CLICKHOUSE_DB=jager
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=secret
    volumes:
      - ./docker/volumes/clickhouse/data:/var/lib/clickhouse
      - ./docker/volumes/clickhouse/logs:/var/log/clickhouse-server
      - ./docker/clickhouse:/docker-entrypoint-initdb.d
    networks:
      - jager-net

  db-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    platform: linux/x86_64
    container_name: jager-db-ui
    ports:
      - '5521:5521'
    depends_on:
      - db

  gm:
    image: kofidahmed/jager
    platform: linux/x86_64
    container_name: jager-gm
    volumes:
      - '.:/app'
    ports:
      - '9990:9990'
    depends_on:
      - db
    command: 
      - ./service.sh 
      - gm:serve
    networks:
      - jager-net

  lm:
    image: kofidahmed/jager
    platform: linux/x86_64
    container_name: jager-lm
    volumes:
      - '.:/app'
    ports:
      - '9991:9991'
    depends_on:
      - db
    command: 
      - ./service.sh 
      - lm:serve
    networks:
      - jager-net

  ta:
    image: kofidahmed/jager
    platform: linux/x86_64
    container_name: jager-ta
    volumes:
      - '.:/app'
    ports:
      - '9992:9992'
    depends_on:
      - db
    command: 
      - ./service.sh 
      - ta:serve
    networks:
      - jager-net

  rs:
    image: kofidahmed/jager
    platform: linux/x86_64
    container_name: jager-rs
    volumes:
      - '.:/app'
    ports:
      - '9993:9993'
    depends_on:
      - db
      - rq
    command: 
      - ./service.sh 
      - rs:serve
    networks:
      - jager-net

  rq:
    image: kofidahmed/jager
    platform: linux/x86_64
    container_name: jager-rq
    volumes:
      - '.:/app'
    command: rq worker --with-scheduler --pid ./logs/rq.pid.log > ./logs/rq.wrk.log 2>&1 &
    depends_on:
      - redis
    networks:
      - jager-net

  experiment:
    image: kofidahmed/jager
    platform: linux/x86_64
    container_name: jager-exp
    volumes:
      - '.:/app'
    command: tail -f /dev/null
    networks:
      - jager-net

networks:
  jager-net:
    driver: bridge