services:
  redis:
    platform: linux/x86_64
    container_name: jager-redis
    image: redis

  db:
    platform: linux/x86_64
    container_name: jager-db
    image: clickhouse/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9009:9009'
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server

  rq:
    container_name: jager-rq
    build:
      context: .
      dockerfile: Dockerfile
    command: rq worker -u redis://redis:6379

  group-manager:
    container_name: group-manager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '9990:9990'
    depends_on:
      - db
    command: 
      - ./service.sh 
      - gm:serve

networks:
  jager:
    driver: bridge

volumes:
  clickhouse_data:
  clickhouse_log: