#!/bin/bash

# Function to setup Python3 virtual env
function runvenv {
    cmd=$1

    if [ -z $cmd ]
        then
        echo "Missing arg to VENV (activate, deactivate, setup)"
        return
    fi

    if [ $cmd == "activate" ] 
        then
        echo "Activating VENV"
        source ./venv/bin/activate
        echo "VENV activated"
    elif [ $cmd == "deactivate" ]
        then
        echo "Deactivating VENV"
        source ./venv/bin/deactivate
        echo "VENV deactivated"
    elif [ $cmd == "setup" ]
        then
        echo "Creating VENV..."
        python3 -m venv venv
        echo "Activating VENV..."
        source ./venv/bin/activate
        echo "Installing Requirements"
        pip install -r requirements.txt
        echo "Virtual Environment Setup Completed"
    else
        echo "Unknown VENV Command"
    fi
}

# Function for app specific commands
function runapp {
    cmd=$1

    if [ -z $cmd ]
        then
        echo "Missing arg to app command (migrate, start)"
        return
    fi

    if [ $cmd == "migrate" ] 
        then
        echo "Running app migrate"
        python3 app.py migrate
    elif [ $cmd == "start" ]
        then
        echo "Starting app"
        flask run
    else
        echo "Unknown App Command"
    fi
}

# Function for data generation commands
function runcdr {
    cmd=$1

    if [ -z $cmd ]
        then
        echo "Missing command to cdr module"
        echo "Available commands: generate"
        return
    fi

    if [ $cmd == "generate" ] 
        then
        echo "Running CDR generator"

        num_carriers=$2
        num_subs=$3

        if [ -z $num_carriers ]
            then
            num_carriers=7000
        fi

        if [ -z $num_subs ]
            then
            num_subs=1000000
        fi

        python3 ./cdrs/generator.py -c $num_carriers -s $num_subs
    else
        echo "Unknown CDR Command"
    fi
}

runvenv activate > /dev/null 2>&1

module=$1
command=$2

if [ -z $module ]
    then
    echo "Missing module (app, cdr, venv)"
    exit 1
fi

if [ $module == "cdr" ] 
    then
    runcdr $command $3 $4
elif [ $module == 'app' ]
    then
    runapp $command
elif [ $module == 'venv' ]
    then
    runvenv $command
else
    echo "Unknown command"
fi